export const SearchActiveStyle = {
  border: "2px solid #222",
  position: "absolute",
  height: "40vh",
  maxHeight: "400px",
  maxWidth: "none",
  width: "inherit",
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  margin: "0 auto",
  padding: "2rem 6rem",
  zIndex: 10,
  background: "#ffffff",
  paddingBtn: "0 1rem",
  maxWidthBtn: "var(--max-width)",
  btnItemWidth: "33.3%",
  borderContainerWidth: "100%",
  topBtn: "50%",
  leftBtn: "50%",
  transform: "translate(-50%, 2rem)",
  bordersMaxWidth: "1232px",
  borderPadding: 0,
  guestBtnHeight: "100%",
};

export const SearchInactiveStyle = {
  position: "relative",
  fontFamily: "Mulish",
  background: "#ffffff",
  justifyContent: "flex-end",
  borderPadding: "0 1em",
  positionAbsolute: "absolute",
  topBtnContainer: 0,
};
